name: hello world
on:
  push:
    paths:
      - "!README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "main"
      - "release/**"
      - "!dev/**"
  pull_request:
    type: [opened, reopened, synchronize]

  workflow_dispatch:
jobs:
  say-hello:
    runs-on: windows-latest
    steps:
      -run: echo this is a engineer
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
      - run: docker image ls
